### ISSUE TITLE
FOB spawns

### ISSUE THREAD

**Issue by DagiDCS** [akaAgar/briefing-room-for-dcs#146]
_Original Title:Suggestions "Carriers and FOB's etc_

Hello, 

For a suggestion, the briefing room should have an option for a single carrier (as now it wants to create a carrier for every flight starting from a carrier.) It would also be a neat feature to get a FOB for helicopter pilots so they don't need to fly over 100 miles with the jets. Also, some aircraft like A10 is extremely slow, so if you would be able to choose another airfield for some specific flight. We also fly in large numbers so the "very high" option on enemies is eliminated kinda fast, so we have added sometimes extra script to spawn destroyed air groups, maybe the briefing room could have spawning hostile cap wings or something.

FOB could also have "mn" limit just like the mission has now.

My buddy also suggested that it would be great if you could export the flight information from the briefing room to the kneeboard builder.

PS: Lovely software! looking forward to new updates, I will support this project with a donation!
Anyways thanks for your time

**Comment by john681611** [comment]
* Ok Carrier duplication should be fixed in the next version.
* FOB stuff I like I can see that being very important once the Hind and AH-64 come out. 
* Spawning slow aircraft closer is something you can do in 5 mins in the mission editor. where It's not so simple for the generator.
Note: You can mix cold and hot starts in the new version so you can delay fast jets significantly with cold starts.

Leaving this open as FOB spawns.
