### ISSUE TITLE
Scenery Infantry Spawns in Sea for Airborne Targets

### ISSUE THREAD

**Issue by GrEaSeLiTeNiN** [akaAgar/briefing-room-for-dcs#346]
### Brief Description:  
Selecting "Scenery Infantry" feature to add static soldiers near a "Planes" target objective puts soldiers in the sea in Marianas map.

### Expected:  
Above feature should be dimmed/disabled for an airborne target (planes).

#### Mission and Template Zip:  
[Missions.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/7901048/Missions.zip)

Mission modified: No

**Comment by john681611** [comment]
You could say: Infantry and men lost at sea that the aircraft is attempting to protect till they can be captured/rescued.  The same issue can happen with ships but once again you could say they are collecting survivors.

I'm hesitant to fix this partly because it's not an easy fix but also because it is also directly because of user action choosing options that may not go together. Eg there is nothing stopping you from attempting a carrier take off in an A-10.
