### ISSUE TITLE
Kneeboard Suggestion

### ISSUE THREAD

**Issue by Wood-VCW3** [akaAgar/briefing-room-for-dcs#354]
### Brief Description: 
 Kneeboard Suggestion 

### How does it work: 
This layout seems to be best for user. 

### Why can't it be done in the ME quickly: 
ME does not generate kneeboard would have to be completed for outside source such as 5JsDatacardGenerator
[KNEEBOARD.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/7921559/KNEEBOARD.zip)

**Comment by john681611** [comment]
These look great. The challenge here is due to it being an image we struggle to split stuff neatly especially when people put in a large number of jets and objectives.

**Comment by john681611** [comment]
Looking at this again I like the idea of separating it into effectively reference sheets

**Comment by john681611** [comment]
## Progress:
### Common
![comms_iemjx23n_1](https://user-images.githubusercontent.com/10814889/153730787-ed9828ba-fc12-4cca-b486-567b5c695bea.jpg)
![comms_iemjx23n_2](https://user-images.githubusercontent.com/10814889/153730789-57528a55-4895-4cfc-89fe-99bceaae0e96.jpg)
![comms_iemjx23n_3](https://user-images.githubusercontent.com/10814889/153730790-910cd18c-6179-4917-a085-1da812011a7c.jpg)
### Aircraft specific Flight Plan
![comms_iemjx23n_7](https://user-images.githubusercontent.com/10814889/153730818-bb054517-64ac-4e74-82e3-a678ba69d4d2.jpg)

**Comment by john681611** [comment]
Just realised it makes way more sense to add Airbases and JTAC to the specific aircraft (it shouldn't be super long anyway)

**Comment by BlackRookSix** [comment]
Might I suggest some re-ordering?  
Page 1: Briefing/Intent, Tasks, Waypoints, Callsigns, Airbases
Page 2: Flight Groups, Remarks* 

(* which are just reminders, and could be an Option to turn off once a player got accustomed to the commands/instructions)

This puts all important information on one page for the immediate-need information, and the rest on subsequent pages.

**Comment by john681611** [comment]
You can always suggest stuff. I'm not sure what runs ordering in DCS apparently its name so I'll look into that. The current design attempts to avoid very ugly double pages which would easily occur if anything went with flight groups. 
I actually rank Tasks & Remarks lowest priority as they really are one time things, you can call for task status as well which makes task kneeboard even more low priority.

 Generally, when I'm playing I generally check airbase and JTAC  info most often and it's useful to have a flight plan due to load-outs and fueling setup at the start. I generally don't check flight groups for radios that often 1 because I can't do A2A tanking to save my life but 2 the radio frequencies are pretty standardised in BR so they get in your head quick. 
 
 I don't actually play DCS properly that often and it's nearly always BR so I'm super biased on this.
