### ISSUE TITLE
Very difficult to generate 1970s coldwar missions

### ISSUE THREAD

**Issue by WangNorthSea** [akaAgar/briefing-room-for-dcs#827]
### Brief Description: 
 
If 'Time Period' selected to 1970s, the generator will always report "Error: No operational units in xxx". Change it to '1980s' will generate missions normally. Template file presented.

### Expected: 
 
[Default.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/13852332/Default.zip)

#### Mission and Template Zip: 

Mission modified: Y/N

**Comment by john681611** [comment]
Yeah this will be caused by this: https://github.com/john681611/dcs-data-miner/tree/main/customDataSets
I've done my best to log when units made it into service.  What you're getting is the fact that there is either

A; I've got a bunch of units going into service too late or ending service too early (I usually round down for entering and up for leaving).
B: ED hasn't created enough units for that era.

This project is open source so if you have the time and the interest to improve it please do.

**Comment by WangNorthSea** [comment]
[Default.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/13859069/Default.zip)
This template will continuously report "Error: No operational units in PlaneBomber for given time period. " or "PlaneAttack". But I checked the source code of BR found that in "PlaneBomber" at least Russia has "Tu-95MS", "Tu-160" and USA has "B-52H" and "S-3B" which meet the requirement of "Time Period".
With "Low-res unis" being selected, I don't understand why this error is reported when there are suitable units available.

**Comment by john681611** [comment]
Yeah confirmed this happens odd thanks for spotting it

**Comment by john681611** [comment]
I did still manage to get Some Plane Attack issues if you can provide some aircraft that you know where operational (not just flying prototypes) it would be appreciated to improve our DB
