### ISSUE TITLE
Enhancement: Option to make JTAC capabilities and availability random

### ISSUE THREAD

**Issue by jkaryan** [akaAgar/briefing-room-for-dcs#83]
### "Issue:"
Every time you generate a CAS mission, JTAC is right there to lase, mark or give coordinates to the target, right where they are.

### Solution:
Add option to randomize their capabilities, so that sometimes you actually don't have other options but to look for the targets yourself.

**Comment by john681611** [comment]
Some missions don't have a JTAC, for example, Search and destroy doesn't even have markers. you can modify the objective config in the files to remove such capablities

**Comment by jkaryan** [comment]
Ideally I'd like for it to be possible to randomize it, but that is of course one way to do it.

Need to try other mission types more, I guess CAS by definition would have someone who knows where the targets are, to an extent at least...

**Comment by john681611** [comment]
Yup, it's more or less. "We are going to attack this target please support us." I mean really it closer works out to "wreck these guys before friendly get there and get damaged".

I get your point and I think it could be a good idea to have some form of randomisation on what support is available not just the marking ability but stuff like CAS/SEAD/Artillery where instead of spawning on takeoff you can request it in. so you can save CAP till they are needed or after hostile SAMS are taken out so they don't get shot down.

Damn it this is what I'm gonna code today

**Comment by john681611** [comment]
Availability isn't random but the option for on or off now exists closing.
